### ISSUE TITLE
v2: ability to mock Connector.Do()/Future/Response in tests

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/go-tarantool#237]
At now it is required to write integration tests with Tarantool to test the code written using `go-tarantool`. I saw this problem while writing tests for [tt](https://github.com/tarantool/tt/tree/fed3a5346f8cd6b499820dcf329f403ac19b681c/cli/connector). I couldn't mock the workflow:

```Go
ret := some_code_to_test(mockConnectorObject) {
    // some code to test
    future := mockConnectorObject.Do(someRequest)
    mock_response, mock_err := future.Get()
    // more code to test
}
if ret != expected {
    t.Errorf("test failed")
}
```
It would be great to have that ability.

**Comment by oleg-jukovec** [comment]
At now the code must be changed when adding new requests.

https://github.com/tarantool/go-tarantool/blob/265f96c9ff5f39e436e7645845fea4589762174d/response.go#L112-L143
https://github.com/tarantool/go-tarantool/blob/265f96c9ff5f39e436e7645845fea4589762174d/response.go#L145-L248

It's better to redesign the interface a bit and get rid of it. This may also be related to the issue:

https://github.com/tarantool/go-tarantool/issues/129

**Comment by oleg-jukovec** [comment]
It would be also nice to highlight that `Future.Err()` does not return an error for all cases. From the Telegram chat:

- `доброго дня, странная ситуация. видимо кончилась память, узнал я об этом только через консоль тарантула.
при всем при этом гошный коннектор ошибку не выдает а просто принимает данные как будто все хорошо.
не подскажите куда копать что бы ошибка явно приходила?` // The user used just Future.Err()
- `future.Err() не декодирует тело ответа msgpack, а ошибка может быть там. Нужно future.Get()/future.GetTyped() вызвать и ловить ошибку от них.`
- `ого. очень и очень не очевидно. спасибо`

**Comment by DerekBum** [comment]
As a first priority task we want to do something with the `Response` struct. Here's some thoughts on how to redesign this struct:

### The first approach is to create the `Response` interface.

We can create an interface:
```
type Response interface {
	Decode() ([]interface{}, error)
	DecodeTyped(res interface{}) error

	Pos() ([]byte, error)
	MetaData() ([]ColumnMetaData, error)
	SQLInfo() ([]SQLInfo, error)
}
```
And make the current `Response` implementation a part of it:
```
type BaseResponse struct {
	requestId uint32
	code      uint32
	// Error contains an error message.
	error string
	buf   smallBuf
}
```
After that, some changes to the `Future` methods needs to be done: all methods that return `*Response` needs to return just the `Response`. User could access old `Data`, `Pos`, `MetaData` and `SQLInfo` fields via `Decode()`, `Pos()`, `MetaData()` or `SQLInfo` methods call respectively.

As example:
```
resp, err := conn.Do(...).Get()
if err != nil {
        ...
}
data, err := resp.Decode()
if err != nil {
        ...
}
// Do something with the response data.
```
Same goes with the `Pos`, `MetaData` and `SQLInfo`.

### The second approach is to create the `Response` interface and create different `Response` types for each `Request` type.

The problem with the first approach is that every request will have `Pos`, `MetaData` and `SQLInfo` methods regardless the actual need in them. Responses on some requests does not have those fields, some have only part of them.

So the idea is to create something like current `Request`s structure:
https://github.com/tarantool/go-tarantool/blob/b2b800b09a8047345b81b8cd9b0a7c258637d7ca/request.go#L820-L824
https://github.com/tarantool/go-tarantool/blob/b2b800b09a8047345b81b8cd9b0a7c258637d7ca/request.go#L841-L844
https://github.com/tarantool/go-tarantool/blob/b2b800b09a8047345b81b8cd9b0a7c258637d7ca/request.go#L850-L853

All in all, the response structure will be something like that:
```
type Response interface {
	Decode() ([]interface{}, error)
	DecodeTyped(res interface{}) error
}
```

```
type BaseResponse struct {
	requestId uint32
	code      uint32
	// Error contains an error message.
	error string
	buf   smallBuf
}
```

```
type SelectResponse struct {
	BaseResponse
        pos []byte
}
```

```
type ExecuteResponse struct {
	BaseResponse
        metaData []ColumnMetaData
        sqlInfo []SQLInfo
}
```

But, there is also a downside from the user experience. Since the interface is minimalistic, to get the `Pos`, `MetaData` or `SQLInfo`, the user needs to try to convert the `Request` instance to the corresponding type first.
As an example:
```
resp, err := conn.Do(InsertRequest).Get()
if err != nil {
        ...
}
data, err := resp.Decode()
if err != nil {
        ...
}
// Do something with the response data.
```
Data is easy accessible for every kind of response (no need to convert to anything). However, 
```
resp, err := conn.Do(SelectRequest).Get()
if err != nil {
        ...
}
selectResp, err := resp.(SelectResponse)
if err != nil {
        ...
}
pos := selectResp.GetPos()
// Do something with the response pos.
```

```
resp, err := conn.Do(ExecuteRequest).Get()
if err != nil {
        ...
}
selectResp, err := resp.(ExecuteResponse)
if err != nil {
        ...
}
metaInfo := selectResp.GetMetaInfo()
sqlInfo := selectResp.GetSQLInfo()
// Do something.
```

### What about user experience?

Which method is more user-friendly? (in case of any more discovered approaches to this problem, I will add them to this Issue).
