### ISSUE TITLE
Disable SSL by default

### ISSUE THREAD

**Issue by oleggator** [tarantool/go-tarantool#301]
Disable SSL support by default (replace `go_tarantool_ssl_disable` tag with `go_tarantool_ssl_enable`).
SSL is used in less than 50% cases, but it breaks cross-compilation due to the use of cgo.

**Comment by Mons** [comment]
Why at all is used go-openssl instead of crypto/tls?

**Comment by oleg-jukovec** [comment]
The idea was to provide a fully compatible solution.

For example, `crypto/tls` does not support [DHE ciphers](
https://github.com/golang/go/issues/7758), but [Tarantool Enterprise does it](https://www.tarantool.io/ru/enterprise_doc/security/#supported-ciphers) + the "official" [GOST engine](https://github.com/gost-engine/engine) could be used instead of third-party implementations on Go.

**Comment by filonenko-mikhail** [comment]
Can we use something like https://github.com/ftomza/gogost?
