### ISSUE TITLE
Create connection from socket fd

### ISSUE THREAD

**Issue by locker** [tarantool/go-tarantool#321]
Currently, to create a connection, the user has to specify a URI. The connector creates a socket and connects it to the given URI under the hood. There are use cases when the user doesn't have a URI but does have a connected socket fd. For example, a socket fd could be inherited from the parent process on fork. We need a way to wrap a raw socket fd number in a connection object.

For more details see the [IPROTO over socketpair](https://www.notion.so/tarantool/IPROTO-over-socketpair-fb5a30dc42a348689655bf75248d9020) design document.

**Comment by oleg-jukovec** [comment]
# Possibly changes from the public interface:

## 1 option

Let's just make a separate uri format (we need to find a suitable URL scheme) for file descriptors and use it with connect:
```Go
conn, err := tarantool.Connect(ctx, "fd://236", opts)
```

## 2 option

Use a `Dialer{}` interface instead of address:
//dialer := tarantool.TtDialer{
//    Username: "foo",
//    Password: "bar",
//}
//dialer := tarantool.TlsDialer{
//    Username: "foo",
//    Password: "bar",
//    KeyFile: "foo/bar/file.key",
//}
dialer := tarantool.FdDialer{
    Fd: 233,
}
dialer := tarantool.Connect(ctx, dialer, opts)
```
### Advantages

- Flexible and testable interface.

### Disadvantages

- This requires refactoring before the task (1-2 days.).
- Users may not like too big changes in the public API.
