### ISSUE TITLE
v2: soft automatic schema reload

### ISSUE THREAD

**Issue by kostja** [tarantool/go-tarantool#7]
Now that the iproto protocol has sc_schema_id, fix the driver to perform "soft" schema reload. 
- load the current schema automatically when connection is established
- include sc_schema_id in queries
- if the response is ER_SCHEMA_CHANGED, reload the schema and re-issue the query.

https://github.com/tarantool/tarantool/issues/1183

**Comment by oleg-jukovec** [comment]
It was decided not to implement the schema reloading since the Tarantool 3.0 allows you to use space names directly. The schema in the connector is not currently used for other purposes.
https://github.com/tarantool/go-tarantool/issues/338

But what we can add a separate helper function to load the actual schema for the user.
