### ISSUE TITLE
How i can custom (un)packing and typed selects and function calls for difficult structure.

### ISSUE THREAD

**Issue by SergeiHaidukov** [tarantool/go-tarantool#87]
Hello!
Thanks you for this library.
I recieved this from CallTyped. How I can packing this to struct type?
![image](https://user-images.githubusercontent.com/9820661/71505719-f33fe100-2886-11ea-8337-c28d2c005b8c.png)

**Comment by funny-falcon** [comment]
It is really pity you ask library developer to develop your application.

Also it is pity you use screenshot in issue instead of text. You could at least convert Data it to JSON, couldn't you?

For example, Data is a slice of two elements. And from your screen shot I could not understand what is type of second element.

And I don't understand: `key -> {"proc":"ob","market":"bitstamp","pair":"BTC_USD"}` - key is a map? Or JSON string?

And if Go is your primary application language, then you'd better design struct type first and then make Lua procedure to return data appropriately.

But netherless:
```go
type Elem struct {
   Key string `msgpack:key`
   Val map[string]map[string]float64 `msgpack:val`
}

var Data [][]Elem
CallTyped(..., &Data)
```

**Comment by SergeiHaidukov** [comment]
I'm sorry for my incompetence. I got it what you mean. Thanks for help!
